version: '3.5'

services:
  mysql-service:
    image: mysql:8.0
    container_name: ci01-mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superMYQLUserPwd
      - MYSQL_DATABASE=${database_default_database}
      - MYSQL_USER=${database_default_username}
      - MYSQL_PASSWORD=${database_default_password}
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: ci01-network
